### ISSUE TITLE
Enhancement: Convert keywords to UPPERCASE

### ISSUE THREAD

**Issue by mcandre** [zeroturnaround/sql-formatter#73]
Could sql-formatter convert all SQL keywords to UPPERCASE? This makes it easier to quickly read through large SQL scripts.

**Comment by badp** [comment]
As a purely display kludge...

```css
.hljs.pgsql .hljs-keyword {
    text-transform: uppercase;
}
```
